export type SceneItemId =
  | 'wave2'
  | 'wave1'
  | 'wave3'
  | 'cutCit1'
  | 'cutCit2'
  | 'cutCit3'
  | 'sun'
  | 'pisa'
  | 'bigben'

export type SceneItemConfig = {
  id: SceneItemId
  src: string
  alt: string
  widthDesktop: string
  widthMobile: string
  left: string
  top: string
  zIndex: number
  revealStart: number
  revealEnd: number
  entryX: number
  entryY: number
  rotateIn: number
  settleRotate: number
  floatName: string
  floatDuration: string
  floatDelay: string
  stringCount: number
}

export type SceneStringConfig = {
  id: string
  src: string
  left: string
  top: string
  widthDesktop: string
  widthMobile: string
  zIndex: number
  revealStart: number
  revealEnd: number
}

export const SCENE_PROGRESS = {
  minNavigateForward: 0.97,
  forwardHoldMs: 1200,
  forwardStep: 0.09,
  backwardStep: 0.12,
  wheelFactor: 0.001,
  touchFactor: 0.0028,
  maxInputStep: 0.085,
} as const

export const SCENE_ITEMS: SceneItemConfig[] = [
  {
    id: 'wave2',
    src: '/images/Married/Wave2.png',
    alt: '',
    widthDesktop: '70vw',
    widthMobile: '74vw',
    left: '15%',
    top: '88%',
    zIndex: 80,
    revealStart: 0.05,
    revealEnd: 0.16,
    entryX: 0,
    entryY: 42,
    rotateIn: -5,
    settleRotate: -2,
    floatName: 'float-wave-a',
    floatDuration: '5.6s',
    floatDelay: '0.2s',
    stringCount: 0,
  },
  {
    id: 'wave2',
    src: '/images/Married/Wave2.png',
    alt: '',
    widthDesktop: '70vw',
    widthMobile: '74vw',
    left: '79%',
    top: '86%',
    zIndex: 80,
    revealStart: 0.05,
    revealEnd: 0.16,
    entryX: 0,
    entryY: 42,
    rotateIn: -5,
    settleRotate: -2,
    floatName: 'float-wave-a',
    floatDuration: '5.6s',
    floatDelay: '0.2s',
    stringCount: 0,
  }, {
    id: 'wave2',
    src: '/images/Married/Wave2.png',
    alt: '',
    widthDesktop: '70vw',
    widthMobile: '74vw',
    left: '-2%',
    top: '86%',
    zIndex: 80,
    revealStart: 0.05,
    revealEnd: 0.16,
    entryX: 0,
    entryY: 42,
    rotateIn: -5,
    settleRotate: -2,
    floatName: 'float-wave-a',
    floatDuration: '5.6s',
    floatDelay: '0.2s',
    stringCount: 0,
  },
  {
    id: 'wave1',
    src: '/images/Married/Wave1.png',
    alt: '',
    widthDesktop: '70vw',
    widthMobile: '78vw',
    left: '15%',
    top: '88%',
    zIndex: 82,
    revealStart: 0.18,
    revealEnd: 0.29,
    entryX: 0,
    entryY: 42,
    rotateIn: 5,
    settleRotate: 1,
    floatName: 'float-wave-b',
    floatDuration: '6.2s',
    floatDelay: '0.4s',
    stringCount: 0,
  },
  {
    id: 'wave1',
    src: '/images/Married/Wave1.png',
    alt: '',
    widthDesktop: '70vw',
    widthMobile: '78vw',
    left: '79%',
    top: '88%',
    zIndex: 82,
    revealStart: 0.18,
    revealEnd: 0.29,
    entryX: 0,
    entryY: 42,
    rotateIn: 5,
    settleRotate: 1,
    floatName: 'float-wave-b',
    floatDuration: '6.2s',
    floatDelay: '0.4s',
    stringCount: 0,
  },
  {
    id: 'wave1',
    src: '/images/Married/Wave1.png',
    alt: '',
    widthDesktop: '70vw',
    widthMobile: '78vw',
    left: '-2%',
    top: '88%',
    zIndex: 82,
    revealStart: 0.18,
    revealEnd: 0.29,
    entryX: 0,
    entryY: 42,
    rotateIn: 5,
    settleRotate: 1,
    floatName: 'float-wave-b',
    floatDuration: '6.2s',
    floatDelay: '0.4s',
    stringCount: 0,
  },
  {
    id: 'wave3',
    src: '/images/Married/Wave3.png',
    alt: '',
    widthDesktop: '70vw',
    widthMobile: '76vw',
    left: '15%',
    top: '95%',
    zIndex: 84,
    revealStart: 0.31,
    revealEnd: 0.42,
    entryX: 0,
    entryY: 40,
    rotateIn: -4,
    settleRotate: -1,
    floatName: 'float-wave-c',
    floatDuration: '5.1s',
    floatDelay: '0.1s',
    stringCount: 0,
  },
  {
    id: 'wave3',
    src: '/images/Married/Wave3.png',
    alt: '',
    widthDesktop: '70vw',
    widthMobile: '76vw',
    left: '-15%',
    top: '95%',
    zIndex: 84,
    revealStart: 0.31,
    revealEnd: 0.42,
    entryX: 0,
    entryY: 40,
    rotateIn: -4,
    settleRotate: -1,
    floatName: 'float-wave-c',
    floatDuration: '5.1s',
    floatDelay: '0.1s',
    stringCount: 0,
  },
  {
    id: 'wave3',
    src: '/images/Married/Wave3.png',
    alt: '',
    widthDesktop: '70vw',
    widthMobile: '76vw',
    left: '80%',
    top: '95%',
    zIndex: 84,
    revealStart: 0.31,
    revealEnd: 0.42,
    entryX: 0,
    entryY: 40,
    rotateIn: -4,
    settleRotate: -1,
    floatName: 'float-wave-c',
    floatDuration: '5.1s',
    floatDelay: '0.1s',
    stringCount: 0,
  },
  {
    id: 'cutCit1',
    src: '/images/Married/CutCit1.png',
    alt: '',
    widthDesktop: '16vw',
    widthMobile: '74vw',
    left: '45%',
    top: '66%',
    zIndex: 56,
    revealStart: 0.47,
    revealEnd: 0.57,
    entryX: 0,
    entryY: 38,
    rotateIn: -7,
    settleRotate: -10,
    floatName: 'float-photo-a',
    floatDuration: '4.8s',
    floatDelay: '0.15s',
    stringCount: 1,
  },
  {
    id: 'cutCit2',
    src: '/images/Married/CutCit2.png',
    alt: '',
    widthDesktop: '20vw',
    widthMobile: '70vw',
    left: '64%',
    top: '68%',
    zIndex: 58,
    revealStart: 0.5,
    revealEnd: 0.6,
    entryX: 0,
    entryY: 38,
    rotateIn: 6,
    settleRotate: 4,
    floatName: 'float-photo-b',
    floatDuration: '4.2s',
    floatDelay: '0.25s',
    stringCount: 1,
  },
  {
    id: 'cutCit3',
    src: '/images/Married/CutCit3.png',
    alt: '',
    widthDesktop: '14vw',
    widthMobile: '66vw',
    left: '31%',
    top: '69%',
    zIndex: 55,
    revealStart: 0.53,
    revealEnd: 0.63,
    entryX: 0,
    entryY: 38,
    rotateIn: 8,
    settleRotate: -8,
    floatName: 'float-photo-c',
    floatDuration: '5.0s',
    floatDelay: '0.05s',
    stringCount: 1,
  },
  {
    id: 'sun',
    src: '/images/Married/OrangeSun.png',
    alt: '',
    widthDesktop: '30vw',
    widthMobile: '48vw',
    left: '50%',
    top: '40%',
    zIndex: 40,
    revealStart: 0.68,
    revealEnd: 0.8,
    entryX: 0,
    entryY: 32,
    rotateIn: 0,
    settleRotate: 0,
    floatName: 'float-sun',
    floatDuration: '8.8s',
    floatDelay: '0s',
    stringCount: 1,
  },
  {
    id: 'pisa',
    src: '/images/Married/Pisa.png',
    alt: '',
    widthDesktop: '50vw',
    widthMobile: '44vw',
    left: '20%',
    top: '50%',
    zIndex: 24,
    revealStart: 0.83,
    revealEnd: 0.97,
    entryX: 0,
    entryY: 48,
    rotateIn: -180,
    settleRotate: -5,
    floatName: 'float-tower-a',
    floatDuration: '5.9s',
    floatDelay: '0.3s',
    stringCount: 1,
  },
  {
    id: 'bigben',
    src: '/images/Married/BigBen.png',
    alt: '',
    widthDesktop: '65vw',
    widthMobile: '40vw',
    left: '80%',
    top: '50%',
    zIndex: 22,
    revealStart: 0.85,
    revealEnd: 0.99,
    entryX: 0,
    entryY: 48,
    rotateIn: 24,
    settleRotate: -6,
    floatName: 'float-tower-b',
    floatDuration: '6.3s',
    floatDelay: '0.2s',
    stringCount: 1,
  },
]

export const SCENE_STRINGS: SceneStringConfig[] = []
